language: python
python:
  - "3.6.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
# test coverage stuff
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search